// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftgoppqehugnprpojrnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0Z29wcHFlaHVnbnBycG9qcm5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NTg5MjAsImV4cCI6MjA2NjIzNDkyMH0.D2aqmjEQC1edStzxuhaPcnJNHWYzuTb7b7VGxntr-tk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);